spring:
  h2:
    console:
      enabled: true
  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: "user"
    password: "password"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: test
      password: test
    basic:
      enabled: false